name: 'Generate Version'
description: 'Generates version strings for NuGet packages based on latest published version'

outputs:
  preview:
    description: 'Preview version for GitHub Packages (X.Y.0-preview.[run].[sha].[attempt])'
    value: ${{ steps.version.outputs.preview }}
  pr:
    description: 'PR version for GitHub Packages (X.Y.0-[pr].[run].[sha].[attempt])'
    value: ${{ steps.version.outputs.pr }}
  release:
    description: 'Release version for NuGet.org (X.Y.0)'
    value: ${{ steps.version.outputs.release }}

runs:
  using: 'composite'
  steps:
    - name: Get latest NuGet version
      id: nuget
      shell: bash
      run: |
        echo "Fetching latest version of Hex1b from NuGet.org..."
        
        # Query NuGet API for all versions
        VERSIONS_JSON=$(curl -s "https://api.nuget.org/v3-flatcontainer/hex1b/index.json" 2>/dev/null || echo '{"versions":[]}')
        
        # Extract the latest stable version (no prerelease suffix)
        LATEST_VERSION=$(echo "$VERSIONS_JSON" | jq -r '.versions | map(select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))) | last // "0.0.0"')
        
        if [ "$LATEST_VERSION" = "null" ] || [ -z "$LATEST_VERSION" ]; then
          LATEST_VERSION="0.0.0"
        fi
        
        echo "Latest stable version on NuGet.org: $LATEST_VERSION"
        echo "latest=$LATEST_VERSION" >> $GITHUB_OUTPUT

    - name: Calculate next version
      id: version
      shell: bash
      run: |
        LATEST_VERSION="${{ steps.nuget.outputs.latest }}"
        
        # Parse major.minor.patch
        MAJOR=$(echo "$LATEST_VERSION" | cut -d'.' -f1)
        MINOR=$(echo "$LATEST_VERSION" | cut -d'.' -f2)
        
        # Increment minor version, reset patch to 0
        NEXT_MINOR=$((MINOR + 1))
        BASE_VERSION="${MAJOR}.${NEXT_MINOR}.0"
        
        echo "Next base version: $BASE_VERSION"
        
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        PREVIEW_VERSION="${BASE_VERSION}-preview.${{ github.run_id }}.${SHORT_SHA}.${{ github.run_attempt }}"
        PR_VERSION="${BASE_VERSION}-pr.${{ github.event.pull_request.number }}.${{ github.run_id }}.${SHORT_SHA}.${{ github.run_attempt }}"
        RELEASE_VERSION="${BASE_VERSION}"
        
        echo "preview=$PREVIEW_VERSION" >> $GITHUB_OUTPUT
        echo "pr=$PR_VERSION" >> $GITHUB_OUTPUT
        echo "release=$RELEASE_VERSION" >> $GITHUB_OUTPUT
        echo "Generated preview version: $PREVIEW_VERSION"
        echo "Generated PR version: $PR_VERSION"
        echo "Generated release version: $RELEASE_VERSION"
