name: 'Generate Version'
description: 'Generates version strings for NuGet packages'

outputs:
  preview:
    description: 'Preview version for GitHub Packages (0.1.[runid]-preview.[attempt].[sha])'
    value: ${{ steps.version.outputs.preview }}
  pr:
    description: 'PR version for GitHub Packages (0.1.[runid]-pr.[attempt].[sha])'
    value: ${{ steps.version.outputs.pr }}
  release:
    description: 'Release version for NuGet.org (0.1.[runid])'
    value: ${{ steps.version.outputs.release }}

runs:
  using: 'composite'
  steps:
    - name: Generate versions
      id: version
      shell: bash
      run: |
        PREVIEW_VERSION="0.1.${{ github.run_id }}-preview.${{ github.run_attempt }}.${{ github.sha }}"
        PR_VERSION="0.1.${{ github.run_id }}-pr.${{ github.run_attempt }}.${{ github.sha }}"
        RELEASE_VERSION="0.1.${{ github.run_id }}"
        echo "preview=$PREVIEW_VERSION" >> $GITHUB_OUTPUT
        echo "pr=$PR_VERSION" >> $GITHUB_OUTPUT
        echo "release=$RELEASE_VERSION" >> $GITHUB_OUTPUT
        echo "Generated preview version: $PREVIEW_VERSION"
        echo "Generated PR version: $PR_VERSION"
        echo "Generated release version: $RELEASE_VERSION"
